# Generated by Django 5.1.5 on 2025-01-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
