# Generated by Django 5.1.5 on 2025-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
