# Generated by Django 5.1.5 on 2025-01-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockData',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('symbol',
                 models.CharField(
                     max_length=10)),
                ('date',
                 models.DateField()),
                ('adjusted_close',
                 models.FloatField()),
                ('portfolio',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='historical_data',
                     to='portfolio.portfolio')),
            ],
            options={
                'unique_together': {
                    (
                        'portfolio',
                        'symbol',
                        'date')},
            },
        ),
    ]
