# Generated by Django 5.1.5 on 2025-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_historicalstockdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstockdata',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
