# Generated by Django 5.2.6 on 2025-10-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_historicalstockdata_options_and_more'),
    ]

    operations = [
    ]
