# Generated by Django 5.2.6 on 2025-10-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_saas_schema'),
        ('portfolio', '0006_auto_20251001_1513'),
    ]

    operations = [
    ]
