# Generated by Django 5.2.6 on 2025-10-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_merge_0002_saas_schema_0006_auto_20251001_1513'),
    ]

    operations = [
    ]
