# Generated by Django 5.2.6 on 2025-10-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20251001_1522'),
    ]

    operations = [
    ]
