# Generated by Django 5.2.6 on 2025-10-02 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def update_institute_domains(apps, schema_editor):
    """Update institute domains to be unique"""
    Institute = apps.get_model('portfolio', 'Institute')

    for i, institute in enumerate(Institute.objects.all()):
        if institute.domain == 'example.com':
            institute.domain = f'company{i+1}.com'
            institute.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_portfolio_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new fields to Institute (without unique constraint first)
        migrations.AddField(
            model_name='institute',
            name='domain',
            field=models.CharField(max_length=255, help_text='company.com', default='example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutes/logos/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='primary_color',
            field=models.CharField(default='#007bff', help_text='Brand color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='institute',
            name='max_users',
            field=models.IntegerField(default=10),
        ),
        
        # Create UserProfile model
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='portfolio.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        # Create InstituteSettings model
        migrations.CreateModel(
            name='InstituteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_analytics', models.BooleanField(default=True)),
                ('allow_risk_analysis', models.BooleanField(default=True)),
                ('allow_ai_features', models.BooleanField(default=True)),
                ('max_portfolios_per_manager', models.IntegerField(default=50)),
                ('data_retention_days', models.IntegerField(default=365)),
                ('require_two_factor', models.BooleanField(default=False)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='portfolio.institute')),
            ],
        ),
        
        # Create UserInvitation model
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Institute Admin'), ('manager', 'Fund Manager'), ('analyst', 'Analyst')], max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='portfolio.institute')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        # Data migration to update domains
        migrations.RunPython(
            code=lambda apps, schema_editor: update_institute_domains(apps, schema_editor),
            reverse_code=lambda apps, schema_editor: None,
        ),
        
        # Now make domain unique
        migrations.AlterField(
            model_name='institute',
            name='domain',
            field=models.CharField(max_length=255, unique=True, help_text='company.com'),
        ),
    ]