"""
Django settings for sandbox_2 project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
import whitenoise



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/




SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"

# SECURITY WARNING: don't run with debug turned on in production!


# ALLOWED_HOSTS = ["localhost", "127.0.0.1", "sandbox_2.herokuapp.com"]
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",  # DISABLED for security - using custom admin
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise.runserver_nostatic",
    "portfolio",
    "advanced_analytics",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Custom templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url
import os

DATABASES = {
    "default": dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# Add this to specify the static files directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'portfolio/static'),
    os.path.join(BASE_DIR,'advanced_analytics/static')
]

# ✅ Add WhiteNoise for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise configuration for better static file serving
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# Authentication redirects
LOGIN_URL = "/login/"  # URL to redirect users to when login is required
LOGIN_REDIRECT_URL = "/portfolio_list"  # URL to redirect to after successful login
LOGOUT_REDIRECT_URL = "/login/"  # URL to redirect to after logout


STATIC_ROOT = BASE_DIR / "staticfiles"

# settings.py
import os
from dotenv import load_dotenv

load_dotenv()

REDIS_URL = os.getenv("REDIS_URL") # Should be your "rediss://..." string from Upstash

if not REDIS_URL:
    print("WARNING: REDIS_URL not set. Using LocMemCache.")
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL, # e.g., "rediss://default:password@host:port"
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # REMOVE explicit SSL settings here if REDIS_URL starts with "rediss://"
                # "CONNECTION_POOL_KWARGS": {"ssl": True}, # REMOVE or COMMENT OUT
                # "CONNECTION_CLASS": "redis.connection.SSLConnection", # REMOVE or COMMENT OUT
                # If you still have issues, you might need to ensure certificate verification
                # is handled correctly, sometimes this helps with cloud providers:
                "CONNECTION_POOL_KWARGS": {
                     "ssl_cert_reqs": None, # Disables client-side cert verification;
                                            # Upstash has valid certs, so this is usually for
                                            # specific network environments or older Python SSL.
                                            # Try without this first.
                }
            }
        }
    }
    # If the above with "ssl_cert_reqs": None doesn't work,
    # try with an empty OPTIONS dict first (most idiomatic for rediss://)
    # "OPTIONS": {
    #     "CLIENT_CLASS": "django_redis.client.DefaultClient",
    # }


SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"






